# docker-compose.yml
version: '3.8'

services:
  db:
    container_name: todolist-db
    image: postgres:16
    environment:
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.d:/docker-entrypoint-initdb.d

volumes:
  pg_data: