### 正常登录请求
POST http://{{host}}:{{port}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "masonlee",
  "password": "admin123"
}

### 登录用户名错误
POST http://{{host}}:{{port}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### 用户名太短
POST http://{{host}}:{{port}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "",
  "password": "admin123"
}

### 密码太短
POST http://{{host}}:{{port}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "1234567"
}

### 用户名太长
POST http://{{host}}:{{port}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin_user_too_long_name_here",
  "password": "admin123"
}

### 密码太长
POST http://{{host}}:{{port}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "very_long_password_that_exceeds_limit_here"
}