### 测试接口 - 登录成功
GET http://{{host}}:{{port}}/api/test/hello
Accept: application/json
Authorization: Bearer {{auth_token}}

### 测试接口 - 登录失败
GET http://{{host}}:{{port}}/api/test/hello
Accept: application/json
Authorization: Bearer none
